

export const wordcloudtemplates = [
{wordcloudname: "persons",
displayName: "Persons",
notes: "These are all terms related to persons",
terms: ["no_people_found"]},
{wordcloudname: "emotions",
displayName: "Emotions",
notes: "These are all terms related to emotions",
terms: ["abandoned","acceptance","adoration","affection","Aggravated","agitated","agressive","alert","amazed","ambitious","amused","anger","angry","animosity","annoyed","anticipation","anxiousness","appreciative","apprehensive","ardent","aroused","ashamed","astonished","attraction","attraction","attraction","awed","betrayed","bewildered","bitter","bliss","blue","boastful","bored","breathless","bubbly","calamitous","calm","camaraderie","cautious","cheerful","cocky","cold","collected","comfortable","compassionate","concerned","confident","confused","contempt","content","courageous","cowardly","crafty","cranky","crazy","cruelty","crummy","crushed","curious","cynic","dark","dejected","delighted","delirious","denial","depression","desire","despair","determined","devastated","disappointed","discouraged","disgust","disheartened","dismal","dispirited","distracted","distressed","dopey","down","dreadful","dreary","eager","ecstatic","embarrassed","emotional detest","empathic","emptiness","enchanted","enigmatic","enlightened","enraged","enthralled","enthusiastic","envy","euphoric","excited","exhausted","expectation","exuberance","fascinated","fear","flabbergasted","fight-or-flight","foolish","frazzled","frustrated","fulfillment","furious","gay","giddy","gleeful","gloomy","goofy","grateful","gratified","greedy","Gray","grief poem","grouchy","grudging","guilty","happy","hate","heartbroken","homesick","hopeful","hopeless","horrified","hostile","humiliated","humored","hurt","hyper ","hysterical","indignation","infatuation","infuriated","inner peace","innocent","insanity","insecure","insecure","inspired poem","interest","intimidated","invidious","irate","irritability","irritated","jaded","jealousy","joy","jubilant","kind","lazy","left out","liberated","lively","loathsome","lonely","longing","love","lovesick","loyal","lust","mad","mean","melancholic","mellow","mercy","merry","mildness","miserable","morbid","mourning","needed","needy","nervous","obscene","obsessed","offended","optimistic","outraged","overwhelmed","pacified","pain","panicky","paranoia","passion","pathetic","peaceful","perturbation","","pessimistic","petrified","pity","playful","pleased","pleasure","possessive","pride","provoked","proud","puzzled","rage","regretful","relief","remorse","resentment","resignation","resolved","sadness","satisfied","scared","scorn","selfish","sensual","sensitive","sexy","shame","sheepish","shocked","shy","sincerity","solemn","somber","sorrow","sorry","spirited","stressed","stress","strong","submissive","superior","surprised","sweet","sympathetic","temperamental","tense","terrified","threatened","thrilled","tired","tranquil","troubled","trust","tormented","uncertainty","uneasiness","unhappy","upset","vengeful","vicious","warm","weary","worn-out","worried","worthless","wrathful","yearning","zesty"],
},
{wordcloudname: "virtues",
displayName: "Virtues",
notes: "These are all terms related to virtues",
terms: ["Acceptance","Assertiveness","Authenticity","Beauty","Caring","Cleanliness","Commitment","Compassion","Confidence","Consideration","Contentment","Cooperation","Courage","Creativity","Detachment","Determination","Dignity","Encouragement","Enthusiasm","Ethical","Excellence","Fairness","Faith","Flexibility","Forgiveness","Friendliness","Generosity","Gentleness","Graciousness","Gratitude","Harmonious","Helpfulness","Honesty","Honor","Hope","Humility","Idealism","Integrity","Imaginative","Joyfulness","Justice","Kindness","Love","Loyalty","Moderation","Modesty","Optimistic","Orderliness","Passionate","Patience","Peace","Perseverance","Preparedness","Purposefulness","Reliability","Respect","Responsibility","Reverence","Self-discipline","Service","Sincerity","Tact","Temperate","Tenacious","Thankfulness","Tolerance","Trust","Truthfulness","Understanding","Unity","Visionary","Wisdom","Wonder"]
}
]
